#!/bin/sh

# Gathers userinput tool(reflash or sysupgrade) going to(7.X.XX or 6.X.XX) over (eth0, eth1, etc)

tool="$1"
going_to="$2"
ref_model="$3"
over="$4"

# Checks the model to see what URL to use to run AP42/AP62/AP440/AP840/AP840e and ask the user what tool to use.
AP="AP840E AP840 AP440 A62 A42 DNA"
Firmwares="7.* 6.*" 
ver=""
NG=""

for model in $AP; do
    if grep -oq "$model" /etc/board.json; then
        ver="$model"
        break
    elif grep -oq "DNA" /etc/device_info; then
        ver="DNA"
        break
    fi
done

for firmware in $Firmwares; do
    if grep -q "$firmware" /etc/fw_core_version; then
        NG="$firmware"
        break
    elif grep -q "$firmware" /etc/fw_ng_version; then
        NG="$firmware"
        break
    fi
done

echo "$tool"
echo "$going_to"
echo "$over"
echo "$NG"
# Run the command based on the model and version

#Sysupgrade path

if [ "$tool" = "sysupgrade" ]; then
    case "$ver" in
       "A42")
           case "$firmware" in
               7.*)
                   echo "AP42 with firmware version 7.*"
                   ;;
               6.*)
                   echo "AP42 with firmware version 6.*"
                   ;;
               *)
                   echo "Unsupported firmware version for AP42"
                   ;;
           esac
           ;;
       "A62")
           case "$firmware" in
               7.*)
                   echo "AP62 with firmware version 7.*"
                   ;;
               6.*)
                   echo "AP62 with firmware version 6.*"
                   ;;
               *)
                   echo "Unsupported firmware version for AP62"
                   ;;
           esac
           ;;
       "AP440")
           case "$firmware" in
               7.*)
                   echo "AP440 with firmware version 7.*"
                   ;;
               6.*)
                   echo "AP440 with firmware version 6.*"
                   ;;
               *)
                   echo "Unsupported firmware version for AP440"
                   ;;
           esac
           ;;
       "AP840")
           case "$firmware" in
               7.*)
                   echo "AP840 with firmware version 7.*"
                   ;;
               6.*)
                   echo "AP840 with firmware version 6.*"
                   ;;
               *)
                   echo "Unsupported firmware version for AP840"
                   ;;
           esac
           ;;
       "AP840E")
           case "$firmware" in
               7.*)
                   echo "AP840e with firmware version 7.*"
                   ;;
               6.*)
                   echo "AP840e with firmware version 6.*"
                   ;;
               *)
                   echo "Unsupported firmware version for AP840e"
                   ;;
           esac
           ;;
       "DNA")
           echo "Sysupgrade not available for DNA"
            ;;
        *)
            echo "No matching device found"
            ;;
    esac
else
    echo "Tool is not set to sysupgrade"
fi

#Reflash Path

if [ "$tool" = "reflash" ]; then
    case "$ver" in
       "A42")
           case "$firmware" in
               7.*)
                   echo "AP42 with firmware version 7.*"
                   ;;
               6.*)
                   echo "AP42 with firmware version 6.*"
                   ;;
               *)
                   echo "Unsupported firmware version for AP42"
                   ;;
           esac
           ;;
       "A62")
           case "$firmware" in
               7.*)
                   echo "AP62 with firmware version 7.*"
                   ;;
               6.*)
                   echo "AP62 with firmware version 6.*"
                   ;;
               *)
                   echo "Unsupported firmware version for AP62"
                   ;;
           esac
           ;;
       "AP440")
           case "$firmware" in
               7.*)
                   echo "AP440 with firmware version 7.*"
                   ;;
               6.*)
                   echo "AP440 with firmware version 6.*"
                   ;;
               *)
                   echo "Unsupported firmware version for AP440"
                   ;;
           esac
           ;;
       "AP840")
           case "$firmware" in
               7.*)
                   echo "AP840 with firmware version 7.*"
                   ;;
               6.*)
                   echo "AP840 with firmware version 6.*"
                   ;;
               *)
                   echo "Unsupported firmware version for AP840"
                   ;;
           esac
           ;;
       "AP840E")
           case "$firmware" in
               7.*)
                   echo "AP840e with firmware version 7.*"
                   ;;
               6.*)
                   echo "AP840e with firmware version 6.*"
                   ;;
               *)
                   echo "Unsupported firmware version for AP840e"
                   ;;
           esac
           ;;
       "DNA")
           echo "Sysupgrade not available for DNA"
            ;;
        *)
            echo "No matching device found"
            ;;
    esac
else
    echo "Tool is not set to sysupgrade"
fi
