#!/bin/sh

# Checks the model to see what command to run AP62 or AP440+.
# Checks the MAC address and stores its' value

echo "
 ▄▄▄██▀▀▀▄▄▄       ███▄ ▄███▓▓█████   ██████     ██▓     ██▓▄▄▄█████▓▄▄▄█████▓ ██▓    ▓█████     ██░ ██ ▓█████  ██▓     ██▓███  ▓█████  ██▀███  
   ▒██  ▒████▄    ▓██▒▀█▀ ██▒▓█   ▀ ▒██    ▒    ▓██▒    ▓██▒▓  ██▒ ▓▒▓  ██▒ ▓▒▓██▒    ▓█   ▀    ▓██░ ██▒▓█   ▀ ▓██▒    ▓██░  ██▒▓█   ▀ ▓██ ▒ ██▒
   ░██  ▒██  ▀█▄  ▓██    ▓██░▒███   ░ ▓██▄      ▒██░    ▒██▒▒ ▓██░ ▒░▒ ▓██░ ▒░▒██░    ▒███      ▒██▀▀██░▒███   ▒██░    ▓██░ ██▓▒▒███   ▓██ ░▄█ ▒
▓██▄██▓ ░██▄▄▄▄██ ▒██    ▒██ ▒▓█  ▄   ▒   ██▒   ▒██░    ░██░░ ▓██▓ ░ ░ ▓██▓ ░ ▒██░    ▒▓█  ▄    ░▓█ ░██ ▒▓█  ▄ ▒██░    ▒██▄█▓▒ ▒▒▓█  ▄ ▒██▀▀█▄  
 ▓███▒   ▓█   ▓██▒▒██▒   ░██▒░▒████▒▒██████▒▒   ░██████▒░██░  ▒██▒ ░   ▒██▒ ░ ░██████▒░▒████▒   ░▓█▒░██▓░▒████▒░██████▒▒██▒ ░  ░░▒████▒░██▓ ▒██▒
 ▒▓▒▒░   ▒▒   ▓▒█░░ ▒░   ░  ░░░ ▒░ ░▒ ▒▓▒ ▒ ░   ░ ▒░▓  ░░▓    ▒ ░░     ▒ ░░   ░ ▒░▓  ░░░ ▒░ ░    ▒ ░░▒░▒░░ ▒░ ░░ ▒░▓  ░▒▓▒░ ░  ░░░ ▒░ ░░ ▒▓ ░▒▓░
 ▒ ░▒░    ▒   ▒▒ ░░  ░      ░ ░ ░  ░░ ░▒  ░ ░   ░ ░ ▒  ░ ▒ ░    ░        ░    ░ ░ ▒  ░ ░ ░  ░    ▒ ░▒░ ░ ░ ░  ░░ ░ ▒  ░░▒ ░      ░ ░  ░  ░▒ ░ ▒░
 ░ ░ ░    ░   ▒   ░      ░      ░   ░  ░  ░       ░ ░    ▒ ░  ░        ░        ░ ░      ░       ░  ░░ ░   ░     ░ ░   ░░          ░     ░░   ░ 
 ░   ░        ░  ░       ░      ░  ░      ░         ░  ░ ░                        ░  ░   ░  ░    ░  ░  ░   ░  ░    ░  ░            ░  ░   ░     
                                                                                                                                                
"


AP="AP440 AP840 A62 A42"
ver=""
mac0="$(grep "f8:d9:b8\|ac:86:74" /sys/class/net/eth0/address)"

for model in $AP; do
    if grep -q "$model" /etc/board.json; then
        ver="$model"
        break
    fi
done

if grep -q "7.1" /etc/fw_core_version; then
   ver="AP71"
fi

echo "This is a $ver, ignore if on 7.1"
echo "James is helping ..." 

# Run the command based on the model and Clean up the output, remove (on scan), etc.
case "$ver" in
    "A42")
       scan_list=$(
            iw dev ap0_0 scan ap-force | grep -A 10 "ac:86:74\|f8:d9:b8" | grep -v "TSF\|interval\|capability\|Supported\|TIM:\|seen:\|elements\|freq:" | sed '/BSS/s/\(BSS.*\)/&\nAP:/' | sed 's/(on ap[0-9]*_[0-9]*)//' | sed '/^BSS/ s/^/\n\n/';
            iw dev ap0_1 scan ap-force | grep -A 10 "ac:86:74\|f8:d9:b8" | grep -v "TSF\|interval\|capability\|Supported\|TIM:\|seen:\|elements\|freq:" | sed '/BSS/s/\(BSS.*\)/&\nAP:/' | sed 's/(on ap[0-9]*_[0-9]*)//' | sed '/^BSS/ s/^/\n\n/';
            iw dev ap0_2 scan ap-force | grep -A 10 "ac:86:74\|f8:d9:b8" | grep -v "TSF\|interval\|capability\|Supported\|TIM:\|seen:\|elements\|freq:" | sed '/BSS/s/\(BSS.*\)/&\nAP:/' | sed 's/(on ap[0-9]*_[0-9]*)//' | sed '/^BSS/ s/^/\n\n/';
            iw dev ap0_3 scan ap-force | grep -A 10 "ac:86:74\|f8:d9:b8" | grep -v "TSF\|interval\|capability\|Supported\|TIM:\|seen:\|elements\|freq:" | sed '/BSS/s/\(BSS.*\)/&\nAP:/' | sed 's/(on ap[0-9]*_[0-9]*)//' | sed '/^BSS/ s/^/\n\n/';
            iw dev ap1_0 scan ap-force | grep -A 10 "ac:86:74\|f8:d9:b8" | grep -v "TSF\|interval\|capability\|Supported\|TIM:\|seen:\|elements\|freq:" | sed '/BSS/s/\(BSS.*\)/&\nAP:/' | sed 's/(on ap[0-9]*_[0-9]*)//' | sed '/^BSS/ s/^/\n\n/';
            iw dev ap1_1 scan ap-force | grep -A 10 "ac:86:74\|f8:d9:b8" | grep -v "TSF\|interval\|capability\|Supported\|TIM:\|seen:\|elements\|freq:" | sed '/BSS/s/\(BSS.*\)/&\nAP:/' | sed 's/(on ap[0-9]*_[0-9]*)//' | sed '/^BSS/ s/^/\n\n/';
            iw dev ap1_2 scan ap-force | grep -A 10 "ac:86:74\|f8:d9:b8" | grep -v "TSF\|interval\|capability\|Supported\|TIM:\|seen:\|elements\|freq:" | sed '/BSS/s/\(BSS.*\)/&\nAP:/' | sed 's/(on ap[0-9]*_[0-9]*)//' | sed '/^BSS/ s/^/\n\n/';
            iw dev ap1_3 scan ap-force | grep -A 10 "ac:86:74\|f8:d9:b8" | grep -v "TSF\|interval\|capability\|Supported\|TIM:\|seen:\|elements\|freq:" | sed '/BSS/s/\(BSS.*\)/&\nAP:/' | sed 's/(on ap[0-9]*_[0-9]*)//' | sed '/^BSS/ s/^/\n\n/';
            iw dev ap2_0 scan ap-force | grep -A 10 "ac:86:74\|f8:d9:b8" | grep -v "TSF\|interval\|capability\|Supported\|TIM:\|seen:\|elements\|freq:" | sed '/BSS/s/\(BSS.*\)/&\nAP:/' | sed 's/(on ap[0-9]*_[0-9]*)//' | sed '/^BSS/ s/^/\n\n/';
            iw dev ap2_1 scan ap-force | grep -A 10 "ac:86:74\|f8:d9:b8" | grep -v "TSF\|interval\|capability\|Supported\|TIM:\|seen:\|elements\|freq:" | sed '/BSS/s/\(BSS.*\)/&\nAP:/' | sed 's/(on ap[0-9]*_[0-9]*)//' | sed '/^BSS/ s/^/\n\n/';
            iw dev ap2_2 scan ap-force | grep -A 10 "ac:86:74\|f8:d9:b8" | grep -v "TSF\|interval\|capability\|Supported\|TIM:\|seen:\|elements\|freq:" | sed '/BSS/s/\(BSS.*\)/&\nAP:/' | sed 's/(on ap[0-9]*_[0-9]*)//' | sed '/^BSS/ s/^/\n\n/';
            iw dev ap2_3 scan ap-force | grep -A 10 "ac:86:74\|f8:d9:b8" | grep -v "TSF\|interval\|capability\|Supported\|TIM:\|seen:\|elements\|freq:" | sed '/BSS/s/\(BSS.*\)/&\nAP:/' | sed 's/(on ap[0-9]*_[0-9]*)//' | sed '/^BSS/ s/^/\n\n/'
        )
        ;;
        
    "A62")
       scan_list=$(
            iw dev ap0_0 scan ap-force | grep -A 10 "ac:86:74\|f8:d9:b8" | grep -v "TSF\|interval\|capability\|Supported\|TIM:\|seen:\|elements\|freq:" | sed '/BSS/s/\(BSS.*\)/&\nAP:/' | sed 's/(on ap[0-9]*_[0-9]*)//' | sed '/^BSS/ s/^/\n\n/';
            iw dev ap0_1 scan ap-force | grep -A 10 "ac:86:74\|f8:d9:b8" | grep -v "TSF\|interval\|capability\|Supported\|TIM:\|seen:\|elements\|freq:" | sed '/BSS/s/\(BSS.*\)/&\nAP:/' | sed 's/(on ap[0-9]*_[0-9]*)//' | sed '/^BSS/ s/^/\n\n/';
            iw dev ap0_2 scan ap-force | grep -A 10 "ac:86:74\|f8:d9:b8" | grep -v "TSF\|interval\|capability\|Supported\|TIM:\|seen:\|elements\|freq:" | sed '/BSS/s/\(BSS.*\)/&\nAP:/' | sed 's/(on ap[0-9]*_[0-9]*)//' | sed '/^BSS/ s/^/\n\n/';
            iw dev ap0_3 scan ap-force | grep -A 10 "ac:86:74\|f8:d9:b8" | grep -v "TSF\|interval\|capability\|Supported\|TIM:\|seen:\|elements\|freq:" | sed '/BSS/s/\(BSS.*\)/&\nAP:/' | sed 's/(on ap[0-9]*_[0-9]*)//' | sed '/^BSS/ s/^/\n\n/';
            iw dev ap1_0 scan ap-force | grep -A 10 "ac:86:74\|f8:d9:b8" | grep -v "TSF\|interval\|capability\|Supported\|TIM:\|seen:\|elements\|freq:" | sed '/BSS/s/\(BSS.*\)/&\nAP:/' | sed 's/(on ap[0-9]*_[0-9]*)//' | sed '/^BSS/ s/^/\n\n/';
            iw dev ap1_1 scan ap-force | grep -A 10 "ac:86:74\|f8:d9:b8" | grep -v "TSF\|interval\|capability\|Supported\|TIM:\|seen:\|elements\|freq:" | sed '/BSS/s/\(BSS.*\)/&\nAP:/' | sed 's/(on ap[0-9]*_[0-9]*)//' | sed '/^BSS/ s/^/\n\n/';
            iw dev ap1_2 scan ap-force | grep -A 10 "ac:86:74\|f8:d9:b8" | grep -v "TSF\|interval\|capability\|Supported\|TIM:\|seen:\|elements\|freq:" | sed '/BSS/s/\(BSS.*\)/&\nAP:/' | sed 's/(on ap[0-9]*_[0-9]*)//' | sed '/^BSS/ s/^/\n\n/';
            iw dev ap1_3 scan ap-force | grep -A 10 "ac:86:74\|f8:d9:b8" | grep -v "TSF\|interval\|capability\|Supported\|TIM:\|seen:\|elements\|freq:" | sed '/BSS/s/\(BSS.*\)/&\nAP:/' | sed 's/(on ap[0-9]*_[0-9]*)//' | sed '/^BSS/ s/^/\n\n/';
            iw dev ap2_0 scan ap-force | grep -A 10 "ac:86:74\|f8:d9:b8" | grep -v "TSF\|interval\|capability\|Supported\|TIM:\|seen:\|elements\|freq:" | sed '/BSS/s/\(BSS.*\)/&\nAP:/' | sed 's/(on ap[0-9]*_[0-9]*)//' | sed '/^BSS/ s/^/\n\n/';
            iw dev ap2_1 scan ap-force | grep -A 10 "ac:86:74\|f8:d9:b8" | grep -v "TSF\|interval\|capability\|Supported\|TIM:\|seen:\|elements\|freq:" | sed '/BSS/s/\(BSS.*\)/&\nAP:/' | sed 's/(on ap[0-9]*_[0-9]*)//' | sed '/^BSS/ s/^/\n\n/';
            iw dev ap2_2 scan ap-force | grep -A 10 "ac:86:74\|f8:d9:b8" | grep -v "TSF\|interval\|capability\|Supported\|TIM:\|seen:\|elements\|freq:" | sed '/BSS/s/\(BSS.*\)/&\nAP:/' | sed 's/(on ap[0-9]*_[0-9]*)//' | sed '/^BSS/ s/^/\n\n/';
            iw dev ap2_3 scan ap-force | grep -A 10 "ac:86:74\|f8:d9:b8" | grep -v "TSF\|interval\|capability\|Supported\|TIM:\|seen:\|elements\|freq:" | sed '/BSS/s/\(BSS.*\)/&\nAP:/' | sed 's/(on ap[0-9]*_[0-9]*)//' | sed '/^BSS/ s/^/\n\n/'
        )
        ;;
        
    "AP440")
          scan_list=$(
            iw dev scan scan ap-force | grep -A 10 "ac:86:74\|f8:d9:b8" | grep "BSS\|signal\|SSID\|channel" | sed 's/(on scan)//g' | sed '/BSS/s/\(BSS.*\)/&\nAP:/' | sed '/^BSS/ s/^/\n/'
        )
        ;;
        
    "AP840")
          scan_list=$(
            iw dev scan scan ap-force | grep -A 10 "ac:86:74\|f8:d9:b8" | grep "BSS\|signal\|SSID\|channel" | sed 's/(on scan)//g' | sed '/BSS/s/\(BSS.*\)/&\nAP:/' | sed '/^BSS/ s/^/\n/'
        )
        ;;

    "AP71")
         scan_list=$(
           ip link set wlan0 up; iw dev wlan0 scan ap-force  | grep -A 10 "ac:86:74\|f8:d9:b8" | grep "BSS\|signal\|SSID\|channel" | sed 's/(on scan)//g' | sed '/BSS/s/\(BSS.*\)/&\nAP:/' | sed '/^BSS/ s/^/\n/' ; ip link set wlan0 down
         )
         ;;

    *)
        echo "No matching device found"
        ;;
esac

echo ""

# Filter out any repeating AP (XX:00, XX:20, XX:40, XX:60, XX:80) (XX:A0, XX:C0, XX:E0)

unique_macs=$(echo "$scan_list" | grep -oE 'BSS [0-9a-fA-F]{2}:[0-9a-fA-F]{2}:[0-9a-fA-F]{2}:[0-9a-fA-F]{2}:[0-9a-fA-F]{2}:[0-9a-fA-F]{1,2}' | awk '{print $2}' | awk -F: '{print $1":"$2":"$3":"$4":"$5":"substr($6, 1, length($6)-1)}' | sort -u)

echo "$unique_macs" | while read -r mac_addresses; do
    addr_match=$(echo "$scan_list" | grep -A 5 -m 1 "$mac_addresses" | sed 's/BSS/\n&/g')
    echo "$addr_match"
done


