#!/bin/sh

# Checks the model to see what command to run AP62 or AP440+.
# Checks the MAC address and stores its' value

AP="AP440 AP840 A62"
ver=""
mac0="$(grep "f8:d9:b8\|ac:86:74" /sys/class/net/eth0/address)"

for model in $AP; do
    if grep -q "$model" /etc/board.json; then
        ver="$model"
        break
    fi
done

# Run the command based on the model and Clean up the output, remove (on scan), etc.
case "$ver" in
    "A62")
       scan_list=$(
            iw dev ap0_2 scan ap-force | grep -A 7 "ac:86:74\|f8:d9:b8" | grep -v "TSF\|interval\|capability\|Supported\|Parameter\|TIM:\|seen:\|elements\|freq" | sed '/BSS/s/\(BSS.*\)/&\nAP:/' | sed 's/(on ap[0-9]*_[0-9]*)//' | sed '/^BSS/ s/^/\n/' ;
            iw dev ap1_2 scan ap-force | grep -A 7 "ac:86:74\|f8:d9:b8" | grep -v "TSF\|interval\|capability\|Supported\|Parameter\|TIM:\|seen:\|elements\|freq" | sed '/BSS/s/\(BSS.*\)/&\nAP:/' | sed 's/(on ap[0-9]*_[0-9]*)//' | sed '/^BSS/ s/^/\n/' ;
            iw dev ap2_2 scan ap-force | grep -A 7 "ac:86:74\|f8:d9:b8" | grep -v "TSF\|interval\|capability\|Supported\|Parameter\|TIM:\|seen:\|elements\|freq" | sed '/BSS/s/\(BSS.*\)/&\nAP:/' | sed 's/(on ap[0-9]*_[0-9]*)//' | sed '/^BSS/ s/^/\n/'
        )
        ;;
        
    "AP440")
          scan_list=$(
            iw dev scan scan ap-force | grep -A 10 "ac:86:74\|f8:d9:b8" | grep "BSS\|signal\|SSID\|channel" | sed 's/(on scan)//g' | sed '/BSS/s/\(BSS.*\)/&\nAP:/' | sed '/^BSS/ s/^/\n/'
        )
        ;;
        
    "AP840")
          scan_list=$(
            iw dev scan scan ap-force | grep -A 10 "ac:86:74\|f8:d9:b8" | grep "BSS\|signal\|SSID\|channel" | sed 's/(on scan)//g' | sed '/BSS/s/\(BSS.*\)/&\nAP:/' | sed '/^BSS/ s/^/\n/'
        )
        ;;
    *)
        echo "No matching device found"
        ;;
esac

# Filter out its own MAC address (XX:00, XX:20, XX:40, XX:60, XX:80) (XX:A0, XX:C0, XX:E0)

mac_prefix="$(echo "$mac0" | awk -F: '{print $1 ":" $2 ":" $3 ":" $4 ":" $5}')"
mac0_matches="$(echo "$scan_list" | grep -A 6 "$mac_prefix")"
mac0_match=$(echo "$scan_list" | awk -v prefix="$mac_prefix" '$0 ~ prefix {print; for(i=1;i<=5;i++) {getline; print}}')

echo "$mac0_match"

# Filter out any repeating AP (XX:00, XX:20, XX:40, XX:60, XX:80) (XX:A0, XX:C0, XX:E0)



# Calculate the suggested dBm based on RSSI value (Lower the dBm by __)



# Output the RSSI scan for partner and suggested RSSI changes based on formula.  
